java -jar closure-compiler.jar --js='main.js' \
  --js='../../blocks/**.js' \
  --js='../../core/**.js' \
  --js='../../generators/**.js' \
  --js='../../msg/js/**.js' \
  --js='../../../closure-library/closure/goog/**.js' \
  --js='../../../closure-library/third_party/closure/goog/**.js' \
  --generate_exports \
  --externs ../../externs/svg-externs.js \
  --compilation_level ADVANCED_OPTIMIZATIONS \
  --dependency_mode=STRICT --entry_point=Main \
  --js_output_file main_compressed.js
