var MSG = {
  title: "PYLY (v00.01.04)",
  blocks: "Blocks",
  debug: "Debug",
  code: "Code",
  fail: "Fail",
  start: ":Start\r\n",
  reallyrun: "ReallRun?",
  stop: "\r\n:Stop",
  copyright:"Copyright © 300 Edu Tech  www.trtos.com",
  likeTooltip: "Save as a sample.",
  likeinputtitle:"New template name:",
  runTooltip: "Program to run the workspace on the target board.",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard all blocks.",
  catGpio:"Gpio",
  catIot:"Iot",
  catPwm:"Pwm",
  catAnalog:"Analog input",
  catI2c:"I2c",
  catSpi:"Spi",
  catSerial:"Serial",
  catFile:"File",
  catSound:"Sound",
  catTcpip:"Tcp/IP",
  catTime:"Time",
  catLcd:"Lcd",
  catLcdBase:"Base",
  catLcdHigh:"High",
  catCamera:"Camera",
  catPrint:"Print",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  listVariable: "list",
  textVariable: "text",
  deletethiscontext:"Delete %1 all %2 blocks?",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  catGpio_write_title:"write io %1 to %2",
  catGpio_read_title:"read io %1",
  catGpio_mode_title:"set io %1 to %2",
  catGpio_value_high:"HIGH",
  catGpio_value_low:"LOW",
  catGpio_mode_out:"OUT",
  catGpio_mode_in:"IN",
  catGPio_interrupt_title:"set interrupt %1  %2",
  catPwm_period_ms_title:"set pwm %1 period %2 ms",
  catPwm_cycle_title:"write pwm %1 cycle %2 /1",
  catPwm_enable_title:"set pwm %1 %2 ",
  catPwm_value_enable:"ENABLE",
  catPwm_value_disenable:"DISENABLE",
  catSound_play_title:"play %1",
  catI2c_address_title:"create %1 address %2",
  catI2c_readreg_title:"read %1 reg %2",
  catI2c_writereg_title:"write %1 reg %2 value %3",
  catI2c_mpu6050_title:"gyroscope get %1",
  catSpi_readwrite_title:"read %1 write %2",
  catSerial_write_title:"send %1 context %2",
  catSerial_writeline_title:"send %1 line %2 ",
  catSerial_write_array_title:"send %1 array %2",
  catSerial_set_baudrate_title:"set %1 baudrate %2",
  catSerial_readstr_title:"read %1 string %2 byte",
  catSound_piano_title:"piano %1 beat %2",
  catSound_melody_title:"melody %1",
  catSound_effect_title:"effect %1",
  catSound_dance_title:"dance %1",
  catSound_playpath_title:"play path %1",
  catAnalog_read_int_title:"read %1 analog",
  catAnalog_read_float_title:"read %1 voltage",
  catEthernet_ipaddress_title: "ipaddress %1 port %2",
  catEthernet_connect_title: "connect server %1",
  catEthernet_send_title: "send %1 context %2",
  catEthernet_revice_title: "revice %1 length %2",
  catPrint_to_title: "print %1 to %2",
  catPrint_console_title: "Console",
  catPrint_lcd_title: "Lcd",
  catPrint_file_title: "File",
  catIot_send_title:"send %1 to %2 id %3",
  catIot_get_title:"get net variable %1",
  catIot_set_title:"set net variable %1 to %2",
  catLcd_writeline_title:"write %1 to lcd",
  catLcd_drawimage_title:"draw image %1 location (x%2y%3)",
  catLcd_drawdot_title:"drawdot location (x%1y%2)color%3",
  catLcd_drawrect_title:"drawrect start (x1%1y1%2)end (x2%3y2%4)color%5",
  catLcd_drawline_title:"drawline start (x1%1y1%2)end (x2%3y2%4)color%5",
  catLcd_drawrectfill_title:"drawrectfill start (x1%1y1%2)end (x2%3y2%4)color%5",
  catLcd_drawcircle_title:"drawcircle location (x%1y%2)radius%3color%4",
  catLcd_drawcirclefill_title:"drawcirclefill location (x%1y%2)radius%3color%4",
  catLcd_drawclear_title:"draw clear %1",
  catLcd_writestring_title:"write string %1 font %2 location(x%3y%4) fontcolor%5 backcolor%6 alpacolor %7 ",
  catLcd_screenshot_title:"screen shot",
  catTime_timeoption_year:"year",
  catTime_timeoption_month:"month",
  catTime_timeoption_day:"day",
  catTime_timeoption_hour:"hour",
  catTime_timeoption_minute:"minute",
  catTime_timeoption_second:"second",
  catTime_getnow_title:"now %1",
  catTime_sleep_title:"sleep %1 s",
  catTime_nowdate_title:"now date",
  catTime_nowtime_title:"now time",
  catTime_timer_title:"timer %1 timing(s)%2 execution %3",
  catTime_timerstart_title:"timer %1 start",
  catTime_thread_title:"thread%1 %2",
  catFile_write_title: "write %1 to %2",
  catFile_create_title: "write %1 create %2",
  catFile_writeline_title: "writeline %1 to %2",
  catFile_read_title: "read %1",
  catFile_readline_title: "read %1 line %2",
  catFile_readlines_title: "readlines %1",
  catFile_wget_title:"get resource %1",
  catI2c_mpu6050_gyro:"Gyro",
  catI2c_mpu6050_acc:"Acc",
  catI2c_mpu6050_temp:"Temp",
  catLcd_dotarray_title:"%1 %2 %3 %4 %5 %6 %7 %8 %9 %10 %11 %12 %13 %14 %15 %16 %17 %18 %19 %20 %21 %22 %23 %24 %25 %26 %27 %28 %29 %30 %31 %32 %33 %34 %35 %36 %37 %38 %39 %40 %41 %42 %43 %44 %45 %46 %47 %48 %49 %50 %51 %52 %53 %54 %55 %56 %57 %58 %59 %60 %61 %62 %63 %64 %65 %66 %67 %68 %69 %70 %71",
  catLcd_drawdotarray_title:"draw dotarray data%1 color%2 backcolor%3",
  catLcd_drawdotarraybit_title:"draw array bit(x %1 y%2) show %3",
  catLcd_drawdotarraymove_title:"draw array move(x %1 y%2)",
  catCamera_take_title:"take %1 photo",
  catCamera_takesize_title:"take %1 size  %2 picture",
};
