var MSG = {
  title: "极客虫 (v00.01.01)",
  blocks: "块",
  linkTooltip: "保存模块并生成链接。",
  runTooltip: "于工作区中运行块所定义的程式。",
  badCode: "程序错误：\n%1",
  timeout: "超过最大执行行数。",
  trashTooltip: "放弃所有块。",
  catGpio:"端口",
  catPwm:"脉冲",
  catAnalog:"模拟输入",
  catI2c:"总线",
  catSpi:"通信",
  catIic:"IIC",
  catSerial:"串口",
  catSound:"声音",
  catLogic: "逻辑",
  catLoops: "循环",
  catMath: "数学",
  catText: "文本",
  catLists: "列表",
  catColour: "颜色",
  catVariables: "变量",
  catFunctions: "函数",
  listVariable: "列表",
  textVariable: "文本",
  httpRequestError: "请求存在问题。",
  linkAlert: "通过这个链接分享您的模块：\n\n%1",
  hashError: "对不起，没有任何已保存的程序对应'%1' 。",
  xmlError: "无法载入您保存的文件。您是否使用其他版本的Blockly创建该文件的？",
  badXml: "XML解析错误：\n%1\n\n选择“确定”以取消您对XML的修改，或选择“取消”以继续编辑XML。",
  catGpio_write_title:"写端口 %1 为 %2",
  catGpio_read_title:"读端口 %1",
  catGpio_mode_title:"设置端口 %1 为 %2",
  catGpio_value_high:"高",
  catGpio_value_low:"低",
  catGpio_mode_out:"输出",
  catGpio_mode_in:"输入",
  catGPio_interrupt_title:"设置中断 %1 %2",
  catPwm_period_ms_title:"设置 %1 脉冲周期 %2 毫秒",
  catPwm_cycle_title:"写入 %1 占空比 %2 /1",
  catPwm_enable_title:"设置 %1 %2 ",
  catPwm_value_enable:"允许",
  catPwm_value_disenable:"禁止",
  catSound_play_title:"播放 %1",
  catI2c_address_title:"创建设备 %1 地址 %2",
  catI2c_readreg_title:"读取 %1 寄存器 %2",
  catSpi_readwrite_title:"读 %1 写 %2",
  catSerial_write_title:"发送 %1 内容 %2",
  catSerial_write_array_title:"发送 %1 数组 %2",
  catSound_piano_title:"钢琴 %1 节拍 %2",
  catSound_melody_title:"旋律 %1",
  catSound_effect_title:"音效 %1",
  catAnalog_read_int_title:"读取 %1 模拟量",
  catAnalog_read_float_title:"读取 %1 电压",
};
